name: proxy_core
version: 0.0.1

description: >
  Proxy core library for Dart.
author: Chenna Reddy <chenna@alavala.in>
homepage: http://github.com/yagnyam-in/proxy-core-dart

environment:
 sdk: '>=2.2.2 <3.0.0'

dependencies:
  json_annotation: ^2.4.0
  quiver: '>=2.0.0 <3.0.0'
  uuid: ^2.0.1
  tuple: ^1.0.2
  http: ^0.12.0+2
  logging: ^0.11.3+2
  crypto: ^2.0.6
  pointycastle: ^1.0.1
  asn1lib: ^0.5.8
  x509csr: ^1.0.2
  encrypt: ^3.2.0

dev_dependencies:
  build_runner: ^1.4.0
  json_serializable: ^3.0.0
  test: '>=0.12.42 <2.0.0'
  mockito: ^4.0.0
